apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: on-data-received-set-location-trigger
spec:
  broker: class-b
  filter:
    attributes:
      type: data-received
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: on-data-received-set-location
---

