apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: on-data-received-set-temp-status-trigger
spec:
  broker: class-a
  filter:
    attributes:
      type: data-received
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: on-data-received-set-temp-status
---

