apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: pubsub-source-subscription
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: eu.gcr.io/krules-dev-254113/dev-01-pubsub-source-subscription:0.1.1
          env:
           - name: GOOGLE_APPLICATION_CREDENTIALS
             value: /var/secrets/google/key.json

          volumeMounts:
            - name: config-krules-volume
              mountPath: /krules/config
            - name: google-cloud-key
              mountPath: /var/secrets/google
#
      volumes:
        - name: config-krules-volume
          configMap:
            name: config-krules
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key
---

